"""
Django settings for CodeTutorials project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from djangocodemirror.settings import *			#djangocodemirror widget


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ep0t%co@qqnmc@d&u1*95_=)9ou^3-@0#7wt45=*-w77mh2q-k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

if DEBUG == True:
	ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']
else:
	ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]'] # Change these hostnames for your production environment


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Project specific

    'spikes',
    'editor',
    'docker',
    'client',
    'resources',
    'tutorials',
    'djangocodemirror',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CodeTutorials.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
        	os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CodeTutorials.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

# The following is where 'collectstatic' puts files for the server to serve

STATIC_ROOT = os.path.join(BASE_DIR, 'static/')


# Docker container creation & runtime options

CONT_OPTS = { # Command line arguments used with docker invocation
	# Argument		Value		Unit
	'--cpus ':		1,		# None
	'--memory=':		64 * 2 ** 20,	# Bytes
	'--pids-limit=':	32,		# None
}

# Change these to '-1' to allow unlimited write and read size to/from the input/output files
CONT_MAXWRITE	= 4 * 2 ** 10
CONT_MAXREAD	= 4 * 2 ** 10

# Container timeout values
CONT_RUNOPTS	= ' '.join(map(lambda opt: opt + str(CONT_OPTS[opt]), CONT_OPTS)) # Don't mess with this
CONT_GRACE	= 10
CONT_TIMEOUT	= 0

os.environ['CONT_RUNOPTS']	= CONT_RUNOPTS
os.environ['CONT_GRACE']	= str(CONT_GRACE)
os.environ['CONT_TIMEOUT']	= str(CONT_TIMEOUT)
